{
  "schema_version": "1.4.0",
  "id": "GHSA-pp84-v3mw-gg4w",
  "modified": "2024-10-10T18:46:20Z",
  "published": "2024-08-27T19:50:54Z",
  "aliases": [],
  "summary": "Taipy 3.1.1 affected by CVEs on flask-core and pymongo",
  "details": "### Summary\nIndirect CVEs affect Taipy 3.1.1\n\n### Details\nTaipy 3.1.1 is affected by two existing CVEs:\nCVE-2024-1681 affects flask-core <4.0.1 and taipy 3.1.1 needs <=4.0.0\nCVE-2024-5629 affects pymongo <4.6.3 and taipy 3.1.1 needs <=4.6.1\n\nPlease see References for further details.\n\n### Patch\nplease upgrade to the following versions:\n\nFixed on patch versions: >=3.1.2\nand on major releases: >=4.0.0\n\n### Impact\npre-commit breaks when using dependency Taipy 3.1.1",
  "severity": [],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "taipy"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "4.0.0"
            }
          ]
        }
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 3.1.1"
      }
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/Avaiga/taipy/security/advisories/GHSA-pp84-v3mw-gg4w"
    },
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-1681"
    },
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-5629"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/Avaiga/taipy"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-84pr-m4jr-85g5"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-m87m-mmvp-v9qm"
    }
  ],
  "database_specific": {
    "cwe_ids": [],
    "severity": "HIGH",
    "github_reviewed": true,
    "github_reviewed_at": "2024-08-27T19:50:54Z",
    "nvd_published_at": null
  }
}