{
  "schema_version": "1.4.0",
  "id": "GHSA-296w-6qhq-gf92",
  "modified": "2023-08-15T23:28:45Z",
  "published": "2022-05-14T02:05:08Z",
  "aliases": [
    "CVE-2014-0481"
  ],
  "summary": "Django denial of service via file upload naming",
  "details": "The default configuration for the file upload handling system in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 uses a sequential file name generation process when a file with a conflicting name is uploaded, which allows remote attackers to cause a denial of service (CPU consumption) by unloading a multiple files with the same name.",
  "severity": [

  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "django"
      },
      "ecosystem_specific": {
        "affected_functions": [
          "django.core.files.storage.Storage.get_available_name"
        ]
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.4.14"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "django"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "1.5.0"
            },
            {
              "fixed": "1.5.9"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "django"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "1.6"
            },
            {
              "fixed": "1.6.6"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2014-0481"
    },
    {
      "type": "WEB",
      "url": "https://github.com/django/django/commit/26cd48e166ac4d84317c8ee6d63ac52a87e8da99"
    },
    {
      "type": "WEB",
      "url": "https://github.com/django/django/commit/30042d475bf084c6723c6217a21598d9247a9c41"
    },
    {
      "type": "WEB",
      "url": "https://github.com/django/django/commit/dd0c3f4ee1a30c1a1e6055061c6ba6e58c6b54d1"
    },
    {
      "type": "WEB",
      "url": "https://www.djangoproject.com/weblog/2014/aug/20/security"
    },
    {
      "type": "WEB",
      "url": "http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html"
    },
    {
      "type": "WEB",
      "url": "http://www.debian.org/security/2014/dsa-3010"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-400"
    ],
    "severity": "MODERATE",
    "github_reviewed": true,
    "github_reviewed_at": "2023-08-15T23:28:45Z",
    "nvd_published_at": "2014-08-26T14:55:00Z"
  }
}