{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2020-13254",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. In cases where a memcached backend does not perform key validation, passing malformed cache keys could result in a key collision, and potential data leakage."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "refsource": "UBUNTU",
                "name": "USN-4381-1",
                "url": "https://usn.ubuntu.com/4381-1/"
            },
            {
                "refsource": "UBUNTU",
                "name": "USN-4381-2",
                "url": "https://usn.ubuntu.com/4381-2/"
            },
            {
                "refsource": "MLIST",
                "name": "[debian-lts-announce] 20200612 [SECURITY] [DLA 2233-2] python-django regression update",
                "url": "https://lists.debian.org/debian-lts-announce/2020/06/msg00016.html"
            },
            {
                "refsource": "DEBIAN",
                "name": "DSA-4705",
                "url": "https://www.debian.org/security/2020/dsa-4705"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2020-c2639662af",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/"
            },
            {
                "url": "https://www.oracle.com/security-alerts/cpujan2021.html",
                "refsource": "MISC",
                "name": "https://www.oracle.com/security-alerts/cpujan2021.html"
            },
            {
                "url": "https://docs.djangoproject.com/en/3.0/releases/security/",
                "refsource": "MISC",
                "name": "https://docs.djangoproject.com/en/3.0/releases/security/"
            },
            {
                "refsource": "MISC",
                "name": "https://groups.google.com/d/msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ",
                "url": "https://groups.google.com/d/msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ"
            },
            {
                "refsource": "CONFIRM",
                "name": "https://www.djangoproject.com/weblog/2020/jun/03/security-releases/",
                "url": "https://www.djangoproject.com/weblog/2020/jun/03/security-releases/"
            },
            {
                "refsource": "CONFIRM",
                "name": "https://security.netapp.com/advisory/ntap-20200611-0002/",
                "url": "https://security.netapp.com/advisory/ntap-20200611-0002/"
            }
        ]
    }
}