{
  "schema_version": "1.4.0",
  "id": "GHSA-6r3c-8xf3-ggrr",
  "modified": "2021-09-22T18:37:22Z",
  "published": "2020-06-24T17:15:26Z",
  "aliases": [

  ],
  "summary": "Directory traversal outside of SENDFILE_ROOT in django-sendfile2",
  "details": "django-sendfile2 currently relies on the backend to correctly limit file paths to `SENDFILE_ROOT`. This is not the case for the `simple` and `development` backends, it is also not necessarily the case for any of the other backends either (it's just an assumption that was made by the original author).\n\nThis will be fixed in 0.6.0 which is to be released the same day as this advisory is made public.\n\nWhen upgrading, you will need to make sure `SENDFILE_ROOT` is set in your settings module if it wasn't already.",
  "severity": [

  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "django-sendfile2"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.6.0"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/moggers87/django-sendfile2/security/advisories/GHSA-6r3c-8xf3-ggrr"
    },
    {
      "type": "WEB",
      "url": "https://github.com/moggers87/django-sendfile2/commit/f870c52398a55b9b5189932dd8caa24efb4bc1e1"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/moggers87/django-sendfile2"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-22"
    ],
    "severity": "MODERATE",
    "github_reviewed": true,
    "github_reviewed_at": "2020-06-18T16:55:25Z",
    "nvd_published_at": null
  }
}