{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2020-25032",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "An issue was discovered in Flask-CORS (aka CORS Middleware for Flask) before 3.0.9. It allows ../ directory traversal to access private resources because resource matching does not ensure that pathnames are in a canonical format."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "url": "https://github.com/corydolphin/flask-cors/releases/tag/3.0.9",
                "refsource": "MISC",
                "name": "https://github.com/corydolphin/flask-cors/releases/tag/3.0.9"
            },
            {
                "refsource": "SUSE",
                "name": "openSUSE-SU-2020:1393",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00028.html"
            },
            {
                "refsource": "SUSE",
                "name": "openSUSE-SU-2020:1415",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00032.html"
            },
            {
                "refsource": "SUSE",
                "name": "openSUSE-SU-2020:1423",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00039.html"
            },
            {
                "refsource": "SUSE",
                "name": "openSUSE-SU-2020:1446",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00048.html"
            },
            {
                "refsource": "DEBIAN",
                "name": "DSA-4775",
                "url": "https://www.debian.org/security/2020/dsa-4775"
            }
        ]
    }
}